version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: caremate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: caremate
      MYSQL_USER: caremate
      MYSQL_PASSWORD: caremate123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - caremate-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: caremate-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - caremate-network

  # CareMate 后端应用
  caremate-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caremate-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=caremate
      - DB_PASSWORD=caremate123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=caremate-secret-key-2024
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - caremate-network

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: caremate-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./uploads:/var/www/uploads
    depends_on:
      - caremate-backend
    networks:
      - caremate-network

volumes:
  mysql_data:
  redis_data:

networks:
  caremate-network:
    driver: bridge 